version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
